var arrLang = {
   'en': {
      'home': 'HOME',
      'about': 'ABOUT US',
      'proj': 'PROJECTS',
      'proj-title':'Projects',
      'gallery': 'REAL ESTATE',
      'contact': 'CONTACT',
      'welcome': 'Your reliable and technologically advanced <br> partner in construction',
      'welcome2':'Additional information',
      'about-iren':'About IrenUPS',
      'gallery-1':'Real Estate',
      'contact-us':'Contact us',
      'h1-course':'Benefits of cooperation',
      'p-course' : 'Over the period of our work, we have gained the trust of our clients and partners by successfully implementing a number of important projects.' ,
      'h3-1-features':'EXPERIENCE',
      'p-1-features':'Our specialists have many years of experience in the construction industry, which dates back to 2006',
      'h3-2-features':'OWN TEAM',
      'p-2-features':'The owner of the company, Andriy Tymchuk, is a co-founder of other successful construction companies, which gives us access to additional resources and expertise',
      'h3-3-features':'MULTIFUNCTIONALITY',
      'p-3-features':'We do not limit ourselves to one type of construction and have experience in various areas, including residential complexes and infrastructure facilities, bridges.',
      'h1-campus': 'Our completed projects',
      'p-campus':'By choosing us, you get a reliable and qualified partner you can trust.',
      'cement-factory':'Cement Plant',
      'cement-factory-about': 'Implementation of energy-saving and environmental technologies on the technological line No. 2 of the cement production at Ivano-Frankivskcement PJSC. Installation of structures and waterproofing for the underground part of the transport gallery.Construction began in 2007 and is still ongoing.<br>Works:<br>- Earthworks for excavating the pit;<br>- Installation of concrete preparation;<br>- Waterproofing works (geotextile, PVC membrane - 2.0);<br>- Installation of reinforcement frames and meshes (bottoms, walls, ceilings);<br>- Pouring concrete for the aforementioned structures at various angles of concrete mix deposition.',
      'olsztyn':'Sports Complex "Urania"',
      'olsztyn-about': 'The reconstruction and expansion of the entertainment-sports complex "Urania" in Olsztyn, carried out for the City Council of Olsztyn during the period from 2021 to 2023, reflect an impressive scope of work aimed at enhancing and modernizing this landmark. Workers completed the covering of the dome with thermal welding steam, followed by painting it in a silver color. These works lasted until mid-June. <br>The surface of the dome is 5 thousand square meters, and its renovation can be likened to mending the heel of a shoe. Undoubtedly, the entire building is vast and impressive in its parameters. The volume of the building is 80 thousand cubic meters. Although the area it occupies is 4.1 thousand square meters, the usable area is 7.7 thousand square meters.',
      'atmo':'Multi-apartment residential buildinп "Atmo"',
      'atmo-about': 'The construction of the multi-apartment residential complex ATMO in Wroclaw for EIFFAGE POLSKA BUDOWNICTWO S.A., which took place from 2021 to 2022, comprises a complex of two 6-story buildings housing 113 high-standard apartments ranging from 26 to 145 square meters. <br>Practically every apartment is equipped with a balcony, loggia, or terrace, while ground floor apartments have their own gardens. Thanks to panoramic windows, the interiors of each apartment will be filled with natural light. Residents also have the option to install air conditioning. The complex features 136 parking spaces in the underground garage, a bicycle storage area, and 6 commercial spaces on the ground floor.',
      's16':'Road S16 Olsztyn-Ełk',
      's16-about': 'The expansion of the S16 expressway in the Warmian-Masurian Voivodeship has been completed. The new section from Borki Wielkie to Mrągowo is over 16 km long and passes near the villages of Borki Wielkie, Sorkwity, Nowe Bagienice, Bagienice, Marcinowo, bypassing Mrągowo from the southwest. Approximately 13 km of the route is part of the S16 expressway, and around 4 km constitute the bypass of Mrągowo, which follows national road No. 59. The road on the S16 section has a two-lane cross-section with two lanes in each direction. On the Mrągowo bypass section, it is mostly a one-lane cross-section (1x2). Access to the expressway is only possible through traffic solutions.',
      'hospital':'St Luke`s Hospital',
      'school':'Lyceum named after Vasil the Great',
      'school-about': 'Construction of the administrative building of the Ivano-Frankivsk Archeparchy of the UGCC in Ivano-Frankivsk, at 11 Shevchenko Street, commissioned by the Ivano-Frankivsk Archeparchial Administration of the Ukrainian Greek-Catholic Church. <br>Construction took place in 2017–2018.<br>A two-story building with a total area of 2188.14 sq.m.',
      'hospital-about': 'Construction of the clinic of the Ivano-Frankivsk Archeparchy of the UGCC in Ivano-Frankivsk, at 20, 22, 26 Garbarska Street and 64 Vasyl`yana Street, commissioned by the Ivano-Frankivsk Archeparchial Administration of the Ukrainian Greek-Catholic Church. <br>Construction took place in 2016–2017.<br>A six-story building with a technical floor, with a total area of 5573.99 sq.m.',
      'iren-all': 'IrenUPS Projects',
      'iren-all-proj': '1. Construction of a production and warehouse facility with social and office premises in Białeżyce for the company SpaceFactory Sp. z o.o., 2021,<br>2. Reconstruction and expansion of the entertainment and sports complex "Urania" in Olsztyn, carried out for the City Council in Olsztyn, 2021-2023,<br>3. Construction of a multi-family residential building ATMO in Wrocław for EIFFAGE POLSKA BUDOWNICTWO S.A., 2021-2022,<br>4. Execution of works related to tunnels and railway tracks for FLC BAU Sp. z o.o., 2022-2023,<br>5. Expansion of the municipal waste disposal plant for WARBUD S.A., 2022,<br>6. Construction of the S6 express road Słupsk-Gdańsk on the section Bożepole Wielkie - beginning of the Trójmiasto bypass road, for PORR, 2022,<br>7. Construction of the S16 road Olsztyn (S51) - Ełk (S61), section Borki Wielkie – Mrągowo, 2022-2023,<br>8. Construction of the S19 road at the junction Kuźnica-Sokółka-Północ (with junction), 2022-2023,<br>9. Construction of a production and warehouse facility in Wrocław for FRONTIER ESTATES POLSKA MANAGEMENT SBU WROCŁAW SP. Z O.O., 2022,<br>10. Reconstruction and expansion of the palace building with a change of purpose for the needs of the State Music School I degree in Krotochwin for DEFERO Sp. z o.o., 2022-2023,<br>',
      'iren-all-proj-2': '11. Thermal modernization works as part of the reconstruction and expansion of the building of the Marshal\'s Office of the Opole Voivodeship (ul. Ostrówek 5-7, Opole) for DEFERO Sp. z o.o., 2022-2023,<br>12. Reconstruction and thermal modernization of the building of the Woyciech Kilar Music School in Katowice according to the contract No. FT.2601.47.2020.ZO, concluded with the Center for Artistic Education and the Complex of State Music Schools, for DEFERO Sp. z o.o., 2022-2023,<br>13. General construction works: Construction of the Center for Culture and Integration on the Market Square in Burzenin for DEFERO Sp. z o.o., 2022-2023,<br>14. Thermal modernization of the building of Primary School No. 2 in Gdańsk, ul. Marusarzówny 10, as part of the project: "G1-Comprehensive energy modernization of educational and sports buildings belonging to the municipality of Gdańsk in 2017-2020" together with the adaptation of the building to the current fire safety regulations, for DEFERO Sp. z o.o., 2022-2023,<br>15. Execution of construction works: Thermal modernization of the building of Primary School No. 12 Kornel Makuszyński in Piotrków Trybunalski, ul. Bełzańska 104/106, as part of the project, for DEFERO Sp. z o.o., 2022-2023,<br>16. Thermal modernization of public buildings in Katowice – Stage I, for DEFERO Sp. z o.o., 2022-2023,<br>17. Construction and reconstruction of Primary School No. 1 in Sułoszowa together with the installation of OZE, for DEFERO Sp. z o.o., 2023,<br>18. Comprehensive modernization and reconstruction of the building of the Municipal Cultural Center in Głowno together with landscaping around the building for DEFERO Sp. z o.o., 2023,<br>19. Expansion and modernization of the municipal waste disposal plant at ul. Zabrzeńska 2, Targówek district, Warsaw, for WYSOWA MOSTY Sp. z o.o., 2022-2023,<br>',
      'monokarbud-all': 'Monokarbud Projects',
      'monokarbud-all-proj': '- Chemical reservoirs - "flotators", 2006 <br>- Monolithic-frame construction of a fire reservoir, 2007 <br>- Construction of a multi-storey residential building, 2007 <br>- Launch of the production line for the manufacture of OSB, DSP panels, 2007 <br>- Reconstruction of cement production, conversion to dry production <br>-Aqua-Park, Ice Arena (Ivano-Frankivsk), 2008 <br>-Residential building monolithic-frame works 2008 -Shopping center "VELES-555", 2008 <br>-Construction and reconstruction of an industrial oil refinery (Nadvirna), 2008 <br>-Reservoir for storing clean water with a capacity of 10,000 m³, 2008 <br> -PVC-C production facility with a capacity of 300,000 tons per year, 2009 <br>-Branch "Rail track cement handling terminal" (Uzhgorod, JSC "Ivano-Frankivskcement"), 2009 <br>-Multi-storey residential building, 2010, <br>Construction of the grain drying complex "RIELA" in Horodenka, 2013 <br>Construction of production and warehouse buildings for LLC "Intelkom", 2013 <br>Reconstruction of technological lines of cement production OJSC "Ivano-Frankivskcement", 2013-2014 <br>',
      'monokarbud-all-proj-2': 'Construction of the "Office-Laboratory Building" in Horodenka, 2015 <br>Reconstruction of the food market and trade pavilions in Ivano-Frankivsk, 2015, 2017 and 2021 <br>Construction of a residential building with integrated commercial premises in Kalush, 2015 <br>Construction of a wind power station LLC "WIND ENERGY" in the locality of Obidnyi, Dolynskyi district, 2016 <br>Construction of the extrusion line OJSC "Specialized Concrete" in the village of Yamnytsia, 2016 and 2018 <br>Construction of multi-family residential buildings with integrated premises for public use in Ivano-Frankivsk, 2016-2020 <br>Construction of the residence of the religious community "Nativity of the Blessed Virgin Mary" of the Ukrainian Greek Catholic Church in Ivano-Frankivsk, 2016 <br>Construction of the polyclinic of the Ivano-Frankivsk Archeparchy of the UGCC in Ivano-Frankivsk, 2016 <br>Construction of the administrative building of the Ivano-Frankivsk Archeparchy of the UGCC in Ivano-Frankivsk, 2017 <br>Construction of the elevator tower at the cement handling terminal TDV "Ivano-Frankivskcement" in Ivano-Frankivsk, 2017 <br>Construction of a family-type hotel-type house in the village of Polianytsia, 2019 <br>Reconstruction of infrastructure facilities PJSC "Ivano-Frankivskcement" (clinker silo, cement mill, workshop), village of Yamnytsia, 2020-2021 <br>Construction of an elevated rail track conveyor bridge 1p PJSC "Specialized Concrete" in the village of Yamnytsia, 2020-2021 <br>Construction of belt conveyor lines LLC "AGRO-SYNTHESIS PODILLYA" in the village of Ulashkivtsi, Ternopil region, 2021 <br>Construction of a private estate "Konopka" in the village of Polianytsia, 2022 <br>Reconstruction of the buildings of the "Promprylad. Renovation" plant to create an innovative public center in Ivano-Frankivsk, 2022-2023 <br>',
      'h1-facility':'Founder',
      'h3-facility':'Andriy Tymchuk',
      'p-facility':'Andriy Tymchuk is the owner of Iren UPS, with 17 years of experience in the construction industry. Since 2006, he has been engaged in construction in Ukraine, and over the past 2 years, he has been rapidly launching and developing IrenUPS in Poland. Andriy Tymchuk is also a co-owner of two other construction companies: Monokarbud and Citadel in Ukraine.',
      'h1-cta' : 'Have questions? <br> Send us anywhere in the world',
      'a-cta': 'Contacts',
      'footer-g':'By choosing us, you get a reliable and qualified partner whom you can trust',
      'footer-g-love': 'made with <i class="fa fa-heart-o"></i> by IrenUPS',
      'h1-about' : 'Mission and History of IrenUPS' ,
      'p-about' : 'The main goal that the company always sets for itself is to maximize customer satisfaction. For this purpose, the construction firm has modern equipment and tools, as well as highly qualified personnel. Currently, the company employs over 120 workers. IrenUPS is a construction firm in Europe that has been successfully operating in the market. We specialize in the construction of residential complexes, individual houses, and bridges. Within a short period of operation, our partners have recognized us as reliable performers capable of implementing complex and large-scale projects within specified deadlines.<br> 2006 - The beginning of the construction company`s activities in Ukraine, LLC "MONOKARBUD." The executive body of the company is the directorate headed by director Andriy Tymchuk. <br> 2017 - LLC "Monokarbud" begins its operations in Warsaw, undertaking the construction of trade and entertainment complexes and residential buildings. <br> 2021 - Establishment of the company Iren Ups in Europe, and its development work continues.',
      'h1-services-about': 'Our services and skills:',
      'p-services-about': '1. Construction of residential complexes: - Expansion of multi-family residential buildings.<br>2. Construction of individual houses: - Implementation of mansion and private residential projects.<br>3. Construction of commercial objects: - Conducting projects for trade and entertainment complexes and other commercial structures.<br>4. Engineering works: - Execution of works related to tunnels, railway tracks, and expressways.<br>5. Construction of bridges and roads: - Expansion and reconstruction of bridges.- Construction of express roads and interchanges.<br>6. Waste disposal and environmental projects: - Construction of municipal waste disposal plants.- Reconstruction and modernization of municipal facilities in accordance with environmental standards.<br>7. Design services: - Proposals in the field of design for residential and commercial projects.<br>8. Reconstruction and thermomodernization: - Reconstruction and thermomodernization of educational and cultural buildings.<br>9. Other general construction works: - Expansion and reconstruction of various objects, including schools, cultural centers, and other public buildings.<br>These are just a few examples of our achievements and skills. We strive to meet the needs of our clients to the maximum and ensure a high standard of construction project execution.',
      'contact-us' : 'Contact Us' ,
      'hsq':'Do you have any questions?',
      'street':'18 Wincentego Pola Street,',
      'tel-time':'Monday to Friday 10:00 to 18:00',
      'e-mail-desk':'Email us your query',
      'send-msg':'Send Message',
      'policies': 'Usage Policy',
      'policies-1-p': '1. Commitment to Quality<br>We strive to achieve a high standard of quality in all aspects of our operations. This includes construction quality, service delivery, customer communication, and project management.<br>2. Continuous Improvement and Transparency<br>We regularly assess our processes and projects to identify opportunities for enhancing quality. Our company is committed to providing transparency and open exchange of information regarding initiatives aimed at improving quality.<br>3. Compliance Assurance<br>We adhere to all relevant standards and requirements in the construction and real estate industry, ensuring compliance of all our projects with applicable laws and regulations.<br>These policies are designed to ensure transparency and adherence to our high standards in all aspects of Iren UPS`s business activities.',
      'policies-1-h1': 'Quality Assurance Policy',
      'policies-2-h1': 'Advertising and Marketing Policy',
      'policies-2-p': '1. Advertising Campaigns and Information Collection<br>We may launch advertising campaigns to promote our products and services. During these campaigns, we may collect aggregated information about interaction with the advertising, such as the number of views and engagements.<br>2. Use of Personal Information for Marketing Purposes<br>We may use collected personal information to personalize marketing materials and offers. We do this to enhance the relevance and effectiveness of our marketing efforts.',
      'policies-3-h1': 'Privacy Policy',
      'policies-3-p': 'Iren UPS company aims to ensure the highest level of protection for the personal data of visitors and customers of our website. This privacy statement explains how we collect, use, disclose, and safeguard any information you provide to us when visiting our site.<br>1. Collection and Use of Information<br>We may collect personal information such as name, contact information, and email when you interact with our website. This information is used solely to provide services and information related to our business activities.<br>2. Use of Cookies<br>We may use cookies and other tracking technologies to enhance user convenience and collect aggregated information about the use of our site. You can configure your web browser to reject cookies, but this may affect some site features.<br>3. Disclosure to Third Parties<br>We do not disclose personal information to third parties without your permission, except when required by law or necessary to provide the services you requested.<br>4. Security Measures<br>We implement appropriate technical and organizational measures to protect your personal data from unauthorized access and use.<br>5. Changes to the Privacy Policy<br>This Privacy Policy may be updated from time to time. Please check this page periodically for the latest changes.<br>Contact Us<br>If you have any questions or concerns about our Privacy Policy, please contact us using the contact information provided.',
      'btn-text-one-translate':'More Projects',
      'btn-text-two-translate':'Click!',
   },
   'pl': {
      'home': 'STRONA GŁÓWNA',
      'about': 'O NAS',
      'proj': 'PROJEKTY',
      'proj-title':'Projekty',
      'gallery': 'NIERUCHOMOŚC',
      'contact': 'KONTAKT',
      'welcome': 'Twój niezawodny i zaawansowany technologicznie <br> partner w budownictwie',
      'welcome2':'Dodatkowe informacje',
      'about-iren':'O IrenUPS',
      'gallery-1':'Nieruchomośc',
      'contact-us':'Skontaktuj się z nami',
      'h1-features':'Korzyści z współpracy',
      'p-features' : 'W ciągu naszej pracy zdobyliśmy zaufanie naszych klientów i partnerów, skutecznie realizując szereg ważnych projektów.' ,
      'h3-1-features':'DOŚWIADCZENIE',
      'p-1-features':'Nasi specjaliści posiadają wieloletnie doświadczenie w branży budowlanej, sięgające 2006 roku',
      'h3-2-features':'WŁASNY ZESPÓŁ',
      'p-2-features':'Właściciel firmy, Andriy Tymchuk, jest współzałożycielem innych udanych firm budowlanych, co daje nam dostęp do dodatkowych zasobów i wiedzy',
      'h3-3-features':'WIELOFUNKCYJNOŚĆ',
      'p-3-features':'Nie ograniczamy się do jednego rodzaju budownictwa i mamy doświadczenie w różnych obszarach, w tym w kompleksach mieszkaniowych, obiektach infrastrukturalnych i mostach.',
      'h1-campus': 'Nasze zrealizowane projekty',
      'p-campus':'Wybierając nas, otrzymujesz niezawodnego i kompetentnego partnera, na którego możesz liczyć.',
      'cement-factory':'Zakład Cementowy',
      'cement-factory-about': 'Wdrożenie energooszczędnych i przyjaznych dla środowiska technologii na linii technologicznej nr 2 produkcji cementu w przedsiębiorstwie Ivano-Frankivskcement SA. Montaż konstrukcji i izolacji wodoodpornej dla podziemnej części galerii transportowej.Prace budowlane rozpoczęły się w 2007 roku i nadal trwają.<br>Prace:<br>- Roboty ziemne przy wykopywaniu wykopu;<br>- Montaż przygotowania betonu;<br>- Prace izolacyjne (geowłóknina, membrana PVC - 2,0);<br>- Montaż ram i siatek zbrojeniowych (dno, ściany, stropy);<br>- Wylewanie betonu dla wspomnianych konstrukcji pod różnymi kątami osadzania mieszanki betonowej.',
      'olsztyn':'Kompleks sportowy "Urania"',
      'olsztyn-about': 'Rekonstrukcja i rozbudowa kompleksu rekreacyjno-sportowego "Urania" w Olsztynie, przeprowadzona na zlecenie Rady Miejskiej w latach 2021–2023, odzwierciedla imponujący zakres prac mających na celu poprawę i modernizację tego zabytku. Robotnicy zakończyli pokrycie kopuły parą termozgrzewalną, a następnie jej pomalowanie na srebrny kolor. Prace te trwały do połowy czerwca. <br>Powierzchnia kopuły wynosi 5 tysięcy metrów kwadratowych, a jej remont można porównać do łatania pięty w bucie. Cały budynek jest niewątpliwie imponujący pod względem parametrów. Objętość budynku wynosi 80 tysięcy metrów sześciennych. Choć zajmuje powierzchnię 4,1 tysiąca metrów kwadratowych, to powierzchnia użytkowa wynosi 7,7 tysiąca metrów kwadratowych.',
      'atmo':'Wielorodzinny budynek mieszkalny "Atmo"',
      'atmo-about': 'Budowa wielorodzinnego kompleksu mieszkalnego ATMO we Wrocławiu dla EIFFAGE POLSKA BUDOWNICTWO S.A., realizowana w latach 2021–2022, obejmuje kompleks dwóch 6-piętrowych budynków z 113 apartamentami o podwyższonym standardzie o powierzchni od 26 do 145 metrów kwadratowych. <br>Praktycznie do każdego mieszkania przynależy balkon, loggia lub taras, a do mieszkań na parterze przynależą własne ogrody. Dzięki panoramicznym oknom wnętrza każdego mieszkania będą pełne naturalnego światła. Mieszkańcy mają również możliwość montażu klimatyzacji. Kompleks posiada 136 miejsc parkingowych w garażu podziemnym, pomieszczenie na rowery oraz 6 lokali usługowych na parterze.',
      's16':'Droga S16 Olsztyn-Ełk',
      's16-about': 'Rozbudowa autostrady szybkiego ruchu S16 w województwie warmińsko-mazurskim została już zakończona. Nowy odcinek Borki Wielkie - Mrągowo ma ponad 16 km długości i przebiega w pobliżu wsi Borki Wielkie, Sorkwity, Nowe Bagienice, Bagienice, Marcinowo, omijając Mrągowo od południowego zachodu. Około 13 km trasy stanowi autostradę szybkiego ruchu S16, a około 4 km to objazd Mrągowa, który biegnie wzdłuż krajowej drogi nr 59. Droga na odcinku S16 ma dwupasmowy przekrój poprzeczny z dwiema krawędziami w każdym kierunku. Na odcinku objazdu Mrągowa jest to droga głównie jednopasmowa (1x2). Dostęp do autostrady jest możliwy tylko przez rozwiązania komunikacyjne.',
      'hospital':'Szpital św. Łukasza',
      'school':'Liceum imienia św. Vasylia Wielkiego',
      'school-about': 'Budowa budynku administracyjnego Archidiecezji Greckokatolickiej we Lwowie w Ivano-Frankivsku przy ul. Szewczenki 11, na zamówienie Administracji Archidiecezji we Lwowie Kościoła Greckokatolickiego. <br>Budowa została zrealizowana w latach 2017–2018.<br=Dwupiętrowy budynek o łącznej powierzchni 2188,14 m².',
      'hospital-about': 'Budowa kliniki Archidiecezji Greckokatolickiej we Lwowie w Ivano-Frankivsku przy ul. Garbarskiej 20,22,26 oraz ul. Wasyljanok 64, na zamówienie Administracji Archidiecezji we Lwowie Kościoła Greckokatolickiego. <br>Budowa została zrealizowana w latach 2016–2017.<br=Sześciopiętrowy budynek z piętrem technicznym, o łącznej powierzchni 5573,99 m².',
      'iren-all': 'Projekty IrenUPS',
      'iren-all-proj': '1. Rozbudowa obiektu produkcyjno-magazynowego z pomieszczeniami socjalnymi i biurowymi w Białeżycach dla firmy SpaceFactory Sp. z o.o., 2021 r.,<br>2. Przebudowa i rozbudowa kompleksu rekreacyjno-sportowego „Urania” w Olsztynie, wykonana dla Rady Miejskiej w Olsztynie, 2021-2023 r.,<br>3. Budowa wielorodzinnego budynku mieszkalnego ATMO we Wrocławiu dla EIFFAGE POLSKA BUDOWNICTWO S.A., 2021-2022 r.,<br>4. Wykonanie prac związanych z tunelami i torami kolejowymi dla FLC BAU Sp. z o.o., 2022-2023 r.,<br>5. Rozbudowa miejskiego zakładu utylizacji odpadów komunalnych dla WARBUD S.A., 2022 r.,<br>6. Budowa autostrady S6 Słupsk-Gdańsk na odcinku Bożepole Wielkie - początek drogi obwodowej Trójmiasta, dla PORR, 2022 r.,<br>7. Budowa drogi S16 Olsztyn (S51) - Ełk (S61), odcinek Borki Wielkie – Mrągowo, 2022-2023 r.,<br>8. Budowa drogi S19 na węźle Kuźnica-Sokółka-Północ (z węzłem), 2022-2023 r.,<br>9. Budowa obiektu produkcyjno-magazynowego we Wrocławiu dla FRONTIER ESTATES POLSKA MANAGEMENT SBU WROCŁAW SP. Z O.O., 2022 r.,<br>10. Przebudowa i rozbudowa budynku pałacu ze zmianą jego przeznaczenia na potrzeby Państwowej Szkoły Muzycznej I stopnia w Krotochwinie dla DEFERO Sp. z o.o., 2022-2023 r.,<br>',
      'iren-all-proj-2': '11. Prace termomodernizacyjne w ramach przebudowy i rozbudowy budynku Urzędu Marszałkowskiego Województwa Opolskiego (ul. Ostrówek 5-7, Opole) dla DEFERO Sp. z o.o., 2022-2023 r.,<br>12. Przebudowa i termomodernizacja budynku Szkoły Muzycznej im. Wojciecha Kilara w Katowicach zgodnie z umową nr FT.2601.47.2020.ZO, zawartą z Centrum Edukacji Artystycznej i Zespołem Szkół Muzycznych dla DEFERO Sp. z o.o., 2022-2023 r.,<br>13. Roboty budowlane: Budowa Centrum Kultury i Integracji na Rynku w Burzeninie dla DEFERO Sp. z o.o., 2022-2023 r.,<br>14. Termomodernizacja budynku Szkoły Podstawowej nr 2 w Gdańsku, ul. Marusarzówny 10, w ramach projektu: „G1-Kompleksowa modernizacja energetyczna budynków edukacyjnych i sportowych gminy Gdańsk w latach 2017-2020” wraz z dostosowaniem budynku do obowiązujących norm bezpieczeństwa przeciwpożarowego dla DEFERO Sp. z o.o., 2022-2023 r.,<br>15. Realizacja prac budowlanych: Termomodernizacja budynku Szkoły Podstawowej nr 12 im. Kornela Makuszyńskiego w Piotrkowie Trybunalskim, ul. Bełzańska 104/106, w ramach projektu dla DEFERO Sp. z o.o., 2022-2023 r.,<br>16. Termomodernizacja budynków użyteczności publicznej w Katowicach – I etap, dla DEFERO Sp. z o.o., 2022-2023 r.,<br>17. Rozbudowa i przebudowa Szkoły Podstawowej nr 1 w Sułoszowej wraz z instalacją OZE, dla DEFERO Sp. z o.o., 2023 r.,<br>18. Kompleksowa modernizacja i przebudowa budynku Miejskiego Centrum Kultury w Głownie wraz z zagospodarowaniem terenu wokół budynku dla DEFERO Sp. z o.o., 2023 r.,<br>19. Rozbudowa i modernizacja miejskiego zakładu utylizacji odpadów przy ul. Zabrzeńska 2, dzielnica Targówek, Warszawa, dla WYSOWA MOSTY Sp. z o.o., 2022-2023 r.,<br>',
      'monokarbud-all': 'Projekty Monokarbud',
      'monokarbud-all-proj': '- Zbiorniki chemiczne - "flotatory", 2006 r. <br>- Budowa monolityczno-szkieletowego zbiornika przeciwpożarowego, 2007 r. <br>- Budowa wielokondygnacyjnego budynku mieszkalnego, 2007 r. <br>- Uruchomienie linii produkcyjnej do produkcji płyt OSB, DSP, 2007 r. <br>- Przebudowa produkcji cementu, przekształcenie technologii na suchą produkcję <br>-Aqua-Park, Lodowisko (m. Ivano-Frankivsk), 2008 r. <br>-Budynek mieszkalny o konstrukcji monolityczno-szkieletowej, 2008 r. -Centrum handlowe „WELES-555”, 2008 r. <br>-Budowa i przebudowa przemysłowej rafinerii nafty (m. Nadvirna), 2008 r. <br>-Zbiornik na czystą wodę o pojemności 10000 m³, 2008 r.<br> -Instalacja do produkcji PVC-C o mocy 300 tys. ton rocznie, 2009 r. <br>-Oddział "Terminal przeładunku torów kolejowych cementu" (m. Uzhgorod, OJSC "Ivano-Frankivskcement"), 2009 r. <br>-Budynek mieszkalny, 2010 r., <br>Budowa kompleksu suszenia ziarna „RIELA” w m. Horodenka, 2013 r.<br>Budowa budynków produkcyjno-magazynowych dla spółki „INTELKOM”, 2013 r.<br>Przebudowa linii technologicznych produkcji cementu OJSC "Ivano-Frankivskcement", 2013-2014 r.<br>',
      'monokarbud-all-proj-2': 'Budowa „Budynku biurowo-laboratoryjnego” w m. Horodenka, 2015 r.<br>Przebudowa rynku spożywczego i pawilonów handlowych w m. Ivano-Frankivsk, 2015 r., 2017 r. i 2021 r.<br>Budowa budynku mieszkalnego z lokalami usługowymi w m. Kalush, 2015 r.<br>Budowa elektrowni wiatrowej spółki „WIND ENERGY” w rejonie Dolyna, 2016 r.<br>Budowa linii ekstrudującej OJSC "Specialized Concrete" we wsi Yamnytsia, 2016 r. i 2018 r.<br>Budowa wielorodzinnych budynków mieszkalnych z wbudowanymi pomieszczeniami użyteczności publicznej w m. Ivano-Frankivsk, 2016-2020 r.<br>Budowa rezydencji wspólnoty religijnej „Bożego Narodzenia Matki Bożej” Ukraińskiego Kościoła Greckokatolickiego w m. Ivano-Frankivsk, 2016 r.<br>Budowa kliniki Archieparchii Greckokatolickiej we Lwowie w m. Ivano-Frankivsk, 2016 r.<br>Budowa budynku administracyjnego Archieparchii Greckokatolickiej we Lwowie w m. Ivano-Frankivsk, 2017 r.<br>Budowa wieży elewatora na terminalu przeładunkowym cementu OJSC "Ivano-Frankivskcement" w m. Ivano-Frankivsk, 2017 r.<br>Budowa domu rodzinengo w stylu hotelowym w s. Polianytsia, 2019 r.<br>Przebudowa obiektów infrastruktury PJSC "Ivano-Frankivskcement" (silos klinkieru, młyn cementowy, warsztat), w. Yamnytsia, 2020-2021 r.<br>Budowa estakady podwyższonej kolei 1p PJSC "Specialized Concrete" we wsi Yamnytsia, 2020-2021 r.<br>Budowa linii taśmociągów PJSC "AGRO-SYNTHESIS PODILLYA" we wsi Ulashkivtsi, obwód Tarnopolski, 2021 r.<br>Budowa prywatnej posiadłości „Konopka” we wsi Polianytsia, 2022 r.<br>Przebudowa budynków zakładu „Promprylad. Renovatsiya” w celu utworzenia innowacyjnego centrum użyteczności publicznej w m. Ivano-Frankivsk, 2022-2023 r. ',
      'h1-facility':'Założyciel',
      'h3-facility':'Andriy Tymchuk',
      'p-facility':'Andriy Tymchuk to właściciel Iren UPS, który ma 17 lat doświadczenia w branży budowlanej. Od 2006 roku zajmuje się budownictwem na Ukrainie, a przez ostatnie 2 lata dynamicznie rozwija IrenUPS w Polsce. Andriy Tymchuk jest także współwłaścicielem dwóch innych firm budowlanych: Monokarbud i Citadel na Ukrainie.',
      'h1-cta' : 'Masz pytania? <br> Wyślij nam wiadomość z dowolnego miejsca na świecie',
      'a-cta': 'Kontakt',
      'footer-g':'Wybierając nas, otrzymujesz niezawodnego i kompetentnego partnera, na którego możesz liczyć',
      'footer-g-love': 'stworzone z <i class="fa fa-heart-o"></i> przez IrenUPS',
      'h1-about' : 'Misja i Historia IrenUPS' ,
      'p-about' : 'Głównym celem, który firma zawsze stawia przed sobą, jest maksymalizacja satysfakcji klienta. W tym celu firma budowlana dysponuje nowoczesnym sprzętem i narzędziami, a także wysoko wykwalifikowanym personelem. Obecnie w firmie pracuje ponad 120 pracowników. IrenUPS to firma budowlana w Europie, która odnosząc sukcesy działa na rynku. Specjalizujemy się w budowie kompleksów mieszkaniowych, indywidualnych domów i mostów. W krótkim czasie nasi partnerzy uznali nas za godnych zaufania wykonawców zdolnych do realizacji skomplikowanych i wielkoskalowych projektów w określonych terminach.<br> 2006 - Początek działalności firmy budowlanej na Ukrainie, LLC "MONOKARBUD". Organem wykonawczym firmy jest dyrekcja pod przewodnictwem dyrektora Andriya Tymchuka. <br> 2017 - LLC "Monokarbud" rozpoczyna działalność w Warszawie, realizując budowę kompleksów handlowo-rozrywkowych i budynków mieszkalnych.<br> 2021 - Założenie firmy Iren Ups w Europie, a prace rozwojowe trwają.',
      'h1-services-about': 'Nasze usługi i umiejętności:',
      'p-services-about': '1. Budowa kompleksów mieszkaniowych: - Rozbudowa wielorodzinnych budynków mieszkalnych.<br>2. Budowa domów indywidualnych: - Realizacja projektów budowy rezydencji i prywatnych obiektów mieszkalnych.<br>3. Budowa obiektów komercyjnych: - Przeprowadzanie projektów kompleksów handlowo-rozrywkowych i innych obiektów komercyjnych.<br>4. Prace inżynieryjne: - Realizacja prac związanych z tunelami, torami kolejowymi i drogami szybkiego ruchu.<br>5. Budowa mostów i dróg: - Rozbudowa i rekonstrukcja mostów.- Budowa dróg szybkiego ruchu i węzłów drogowych.<br>6. Utylizacja odpadów i projekty ekologiczne: - Budowa komunalnych zakładów utylizacji odpadów.- Rekonstrukcja i modernizacja obiektów komunalnych z uwzględnieniem standardów ekologicznych.<br>7. Usługi projektowe: - Propozycje w dziedzinie projektowania dla obiektów mieszkalnych i komercyjnych.<br>8. Rekonstrukcja i termomodernizacja: - Rekonstrukcja i termomodernizacja budynków o charakterze edukacyjnym i kulturalnym.<br>9. Inne prace budowlane: - Rozbudowa i rekonstrukcja różnorodnych obiektów, w tym szkół, centrów kulturalnych i innych budynków publicznych.<br>To tylko kilka przykładów naszych osiągnięć i umiejętności. Dążymy do maksymalnego zaspokajania potrzeb naszych klientów i zapewniania wysokiego standardu realizacji projektów budowlanych.',
      'contact-us' : 'Skontaktuj się z nami' ,
      'hsq':'Masz jakieś pytania?',
      'street':'Ul. Wincentego Pola 18,',
      'tel-time':'Poniedziałku do piątku 10:00 do 18:00',
      'e-mail-desk':'Wyślij nam swoje zapytanie',
      'send-msg':'Wyślij wiadomość',
      'policies': 'Polityka Korzystania',
      'policies-1-p': '1. Zobowiązanie do Jakości<br>Dążymy do osiągnięcia wysokiego standardu jakości we wszystkich aspektach naszej działalności. Obejmuje to jakość budowy, świadczenia usług, komunikację z klientami oraz zarządzanie projektami.<br>2. Ciągłe doskonalenie i Transparentność<br>Regularnie oceniamy nasze procesy i projekty, aby zidentyfikować możliwości poprawy jakości. Nasza firma zobowiązuje się do zapewniania transparentności i otwartej wymiany informacji dotyczącej działań mających na celu podniesienie jakości.<br>3. Zapewnienie Zgodności<br>Przestrzegamy wszystkich odpowiednich standardów i wymagań w branży budowlanej i nieruchomości, zapewniając zgodność wszystkich naszych projektów z obowiązującym prawem i aktami normatywnymi.<br>Te polityki mają na celu zapewnienie transparentności i przestrzegania naszych wysokich standardów we wszystkich aspektach działalności firmy Iren UPS.',
      'policies-1-h1': 'Polityka Zapewnienia Jakości',
      'policies-2-h1': 'Polityka Reklamy i Marketingu',
      'policies-2-p': '1. Kampanie Reklamowe i Zbieranie Informacji<br>Możemy uruchamiać kampanie reklamowe w celu promocji naszych produktów i usług. W trakcie tych kampanii możemy gromadzić zagregowane informacje dotyczące interakcji z reklamą, takie jak liczba wyświetleń i interakcji.<br>2. Wykorzystanie Danych Osobowych w Celach Marketingowych<br>Możemy używać zebranych danych osobowych do personalizacji materiałów marketingowych i ofert. Robimy to w celu zwiększenia istotności i skuteczności naszych działań marketingowych.',
      'policies-3-h1': 'Polityka Prywatności',
      'policies-3-p': 'Firma Iren UPS dąży do zapewnienia najwyższego poziomu ochrony danych osobowych odwiedzających i klientów naszej witryny. Niniejsze oświadczenie o prywatności wyjaśnia, w jaki sposób zbieramy, używamy, ujawniamy i zabezpieczamy wszelkie informacje, które nam przekazujesz podczas odwiedzania naszej witryny.<br>1. Zbieranie i Używanie Informacji<br>Możemy zbierać dane osobowe, takie jak imię, dane kontaktowe i adres e-mail, gdy współdziałasz z naszą witryną. Te informacje są wykorzystywane wyłącznie do świadczenia usług i udostępniania informacji związanych z naszą działalnością.<br>2. Użycie plików cookie<br>Możemy używać plików cookie i innych technologii śledzenia w celu poprawy wygody użytkownika oraz zbierania zagregowanych informacji o korzystaniu z naszej witryny. Możesz skonfigurować swoją przeglądarkę internetową w celu odrzucenia plików cookie, ale może to wpłynąć na niektóre funkcje witryny.<br>3. Ujawnianie informacji stronom trzecim<br>Nie ujawniamy danych osobowych stronom trzecim bez twojej zgody, chyba że jest to wymagane przez prawo lub konieczne do świadczenia żądanych usług.<br>4. Środki bezpieczeństwa<br>Wdrażamy odpowiednie środki techniczne i organizacyjne, aby chronić twoje dane osobowe przed nieuprawnionym dostępem i użyciem.<br>5. Zmiany w polityce prywatności<br>Ta polityka prywatności może być aktualizowana od czasu do czasu. Prosimy regularnie sprawdzać tę stronę, aby dowiedzieć się o najnowszych zmianach.<br>Kontakt<br>Jeśli masz jakiekolwiek pytania lub obawy dotyczące naszej polityki prywatności, skontaktuj się z nami, korzystając z podanych danych kontaktowych.',
      'btn-text-one-translate': 'Więcej projektów',
      'btn-text-two-translate': 'Kliknij!',
   },
   
   'ua': {
      'home': 'ГОЛОВНА',
      'about': 'ПРО НАС',
      'proj': 'ПРОЕКТИ',
      'proj-title':'Проекти',
      'gallery': 'НЕРУХОМІСТЬ',
      'contact': 'КОНТАКТ',
      'welcome': 'Ваш надійний та технологічно досвідчений <br> партнер в будівництві',
      'welcome2': 'Додаткова інформація',
      'about-iren': 'Про IrenUPS',
      'gallery-1': 'Нерухомість',
      'contact-us': 'Зв`яжіться з нами',
      'h1-course': 'Переваги співпраці',
      'p-course': 'Протягом нашої роботи ми здобули довіру наших клієнтів та партнерів, успішно реалізовуючи кілька важливих проектів.',
      'h3-1-features': 'ДОСВІД',
      'p-1-features': 'Наші спеціалісти мають багаторічний досвід у будівельній галузі, який налічується з 2006 року',
      'h3-2-features': 'ВЛАСНА КОМАНДА',
      'p-2-features': 'Власник компанії, Андрій Тимчук, є співзасновником інших успішних будівельних компаній, що дає нам доступ до додаткових ресурсів та експертизи',
      'h3-3-features': 'БАГАТОФУНКЦІОНАЛЬНІСТЬ',
      'p-3-features': 'Ми не обмежуємо себе одним видом будівництва і маємо досвід у різних галузях, включаючи житлові комплекси та об\'єкти інфраструктури, мости.',
      'h1-campus': 'Наші завершені проекти',
      'p-campus': 'Обираючи нас, ви отримуєте надійного та кваліфікованого партнера, на якого можна покластися.',
      'cement-factory': 'Цементний завод',
      'cement-factory-about':'Впровадження енергозберігаючих та природоохоронних технологій на технологічній лінії No2 цементного виробництва ПАТ “Івано-Франківськцемент”. Влаштування конструкцій та гідроізоляції підземної частини транспортної галереї.Будівництво розпочалося у 2007 році і триває досі..<br>Роботи :<br>- земляні роботи по копці котловану; <br>- влаштування бетонної підготовки;<br>- гідроізоляційні роботи (геотекстиль, ПВХ мембрана – 2,0)<br>- влаштування арматурних каркасів та сіток (днища, стін, перекриття); <br>- бетонування вищевказаних конструкцій під різним кутом залягання бетонної суміші.',
      'olsztyn': 'Спортивний комплекс "Уранія"',
      'olsztyn-about':'Реконструкція та розбудова розважально-спортивного комплексу "Urania" в Ольштині, виконана для Міської ради в Ольштині протягом періоду з 2021 по 2023 роки, відображає вражаючий обсяг робіт, які призначені покращити та модернізувати цей визначний об`єкт. Робочі завершили покриття 300 квадратних метрів купола термозварювальною парою та подальше його фарбування у сріблястий колір. Ці роботи тривали до середини червня. <br>Поверхня купола становить 5 тисяч квадратних метрів, а його ремонт можна порівняти з вправою замші у п`ятку взуття. Великим, без сумніву, є весь будинок, який вражає своїми параметрами. Об`єм будівлі складає 80 тисяч кубічних метрів. Хоча площа, яку він займає, становить 4,1 тисячі квадратних метрів, корисна площа становить 7,7 тисяч квадратних метрів.',
      'atmo': 'Багатоквартирний житловий будинок "Atmo"',
      'atmo-about':'Будівництво багатоквартирного житлового комплексу ATMO у Вроцлаві для EIFFAGE POLSKA BUDOWNICTWO S.A., що тривало в період з 2021 по 2022 роки, представляє собою комплекс із двох 6-поверхових будинків, в яких розташовано 113 апартаментів високого стандарту, площею від 26 до 145 квадратних метрів. <br>Практично до кожного квартири призначений балкон, лоджія або тераса, а до квартир на першому поверсі - власний садок. Завдяки панорамним вікнам, внутрішні приміщення кожної квартири будуть наповнені природним світлом. Мешканці також можуть скористатися можливістю установки кондиціонерів. Комплекс має 136 паркомісць у підземному гаражі, місце для зберігання велосипедів, а також 6 торговельних приміщень на першому поверсі.',
      's16': 'Дорога S16 Ольштин-Ельк',
      's16-about':'Розширення швидкісної автомагістралі S16 в Вармінсько-Мазурському воєводстві вже завершено. Новий відрізок Борки-Великі - Мронгово має довжину понад 16 км і пролягає поблизу сіл Борки-Великі, Сорквіти, Нове Баґєніце, Баґєніце, Марцінково, об`їжджаючи Мронгово з південного заходу. Близько 13 км маршруту є швидкісною автомагістраллю S16, а приблизно 4 км представляють об`їзну дорогу Мронгово, яка проходить по національній дорозі № 59. Дорога на ділянці S16 має двосмуговий поперечний переріз з по дві смуги в кожному напрямку. На ділянці об`їзду Мронгово це є дорогою із переважно односмуговим поперечним перерізом (1х2). Доступ до швидкісної дороги можливий лише через транспортні розв`язки.',
      'hospital': 'Лікарня святого Луки',
      'hospital-about':'Будівництво поліклініки Івано-Франківської Архієпархії УГКЦ в м. Івано-Франківськ по вул. Гарбарська, 20,22,26 та вул. Васильянок, 64 на замовлення Івано-Франківського Архієпархіального Управління Української Греко-Католицької Церкви. <br>Будівництво здійснено у 2016 – 2017 році.<br>Шестиповерхова будівля + технічний поверх., загальна площа будинку – 5573,99 м.кв.',
      'school': 'Ліцей імені Василія Великого',
      'school-about':'Будівництво адміністративної будівлі Івано-Франківської Архієпархії УГКЦ в м. Івано-Франківськ по вул. Шевченка 11, на замовлення Івано-Франківського Архієпархіального Управління Української Греко-Католицької Церкви. <br>Будівництво здійснено у 2017 – 2018 році.<br>Двоповерхова будівля, загальна площа будівлі 2188,14 м.кв.',
      'iren-all':'Проекти IrenUPS',
      'iren-all-proj':'1.Розбудова виробничо-складського приміщення з соціальними та офісними приміщеннями в Бялежице для фiрми SpaceFactory ТзОВ, 2021 року.,<br>2. Реконструкція та розбудова розважально-спортивного комлексу «Urania» в Ольштині, виконана для Міської ради  в Ольштинi, 2021-2023 р.,<br>3. Будівництво багатоквартирного житлового будинку ATMO у Вроцлаві, для EIFFAGE POLSKA BUDOWNICTWO S.A., 2021-2022 років.,<br>4. Виконання робіт, пов`язаних з тунелями та залізничними коліями для FLC BAU Sp. z o. o., 2022-2023 р.,<br>5. Розбудова муніципального заводу з утилізації побутових відходів для WARBUD S.A., 2022 р.,<br>6. Будівництво швидкісної дороги S6 Słupsk-Gdańsk на ділянці Bożepole Wielkie - початок об`їзної дороги Trójmiasta, для PORR, 2022 р.,<br>7. Будівництво дороги S16 Ольштин (S51) - Елк (S61), ділянка Borki Wielkie – Mrągowo, 2022-2023 р.,<br>8. Будівництво дороги S19 на розв`язці Kuźnica-Sokółka- Północ (з розв`язкою) 2022-2023 р.,<br>9. Будова виробничо-складського приміщення, Вроцлав, для FRONTIER ESTATES POLSKA MANAGEMENT SBU WROCŁAW SP. З О.О., 2022 р.,<br>10. Реконструкція та розбудова будівлі палацу зі зміною цільового призначення на потреби Державної Музичної Школи I ступеня в Кротошині, для DEFERO ТзОВ, 2022-2023 р.,<br>',
      'iren-all-proj-2':'11.Роботи термомодернізаційнi в рамках реконструкції та розбудови будівлі ДержУстанови Управління Маршалка Опольського Воєводства (ul. Ostrówek 5-7, Opole) для DEFERO ТзОВ, 2022-2023 р.,<br>12.Реконструкція та термомодернізація будівлі КДМШ ім. Войцеха Кілара в Катовіце згiдно договору № FT.2601.47.2020.ZO, укладеного із Центром Mистецької Освіти та Комплексом Державних музичних шкіл, для DEFERO ТзОВ, 2022-2023 р.,<br>13. Загальнобудівельні роботи: Будівництво Центру культури та інтеграції Ринкова площа в Burzeninie, для DEFERO ТзОВ, 2022-2023 р.,<br>14. Термомодернізація будівлі початкової школи № 2 у Гданську, вул. Marusarzówny 10 в рамках проекту: «G1-Комплексна енергетична модернізація освітніх і спортивних будівель, що належать гміні Гданськ у 2017-2020 рр.» разом з адаптацією будівлі до діючих норм пожежної безпеки, для DEFERO ТзОВ, 2022-2023 р.,<br>15. Виконання будівельних робіт:  Термомодернізація будівлі ЗОШ No12. Kornel Makuszyńskiego в Piotrków Tribunalski ul. Белзацька 104/106 в рамках проекту, для DEFERO ТзОВ, 2022-2023 р.,<br>16. Термомодернізація громадських будівель в Катовiцах– І етап , для DEFERO ТзОВ, 2022-2023 р.,<br>17. Розбудова та реконструкція початкової школи № 1 у Sułoszowa разом із встановленням OЗЕ, для DEFERO ТзОВ, 2023 р.,<br>18.Комплексна модернізація та реконструкція будівлі Міського культурного центру в Głowno разом із благоустроєм навколо будівлі для DEFERO ТзОВ, 2023 р.,<br>19. Розбудова та модернізація муніципального заводу з утилізації відходів на вулиці Забженецька, 2, район Таргувек, м.Варшава, для WYSOWA MOSTY Sp. z o. o., 2022 -2023 р.,',
      'monokarbud-all':'Проекти Монокарбуд',
      'monokarbud-all-proj':'- Хімічні резервуари – "флотатори", 2006 р. <br>- Монолітно–каркасне будівництво пожежного резервуару, 2007 р. <br>- Будівництво багатоповерхового житлового будинку, 2007 р. <br>- Запуск лінії виробництва по виготовленню плит OSB, ДСП, 2007 р. <br>- Реконструкція цементного виробництва переведення технології на сухий спосіб виготовлення <br>-Аква-Парк, Льдова арена (м. Івано – Франківськ), 2008 р. <br>-Житловий будинок монолітно-каркасні роботи 2008р. -ТЦ „ВЕЛЕС-555”, 2008 р. <br>-Будівництво і реконструкція промислового нафтопереробного заводу (м. Надвірна), 2008 р. <br>-Резервуар для зберігання чистої води на 10000 м.куб, 2008 р.<br> -Установка по виробництву ПВХ-С потужністю 300 тис. тон в рік, 2009 р. <br>-Філія “Терміналу залізничного полотна перевантаження цементу” (м. Ужгород, ВАТ “Івано-Франківськцемент”), 2009 р. <br>-Багатоквартирний житловий будинок, 2010 р., <br>Будівництво зерносушильного комплексу «RIELA» у м. Городенка, 2013 р.<br>Будівництво виробничо-складських корпусів ТОВ «Інтелком», 2013 р.<br>Реконструкція технологічних ліній цементного виробництва ПАТ «Івано-Франківськцемент», 2013-2014 р.<br>',
      'monokarbud-all-proj-2':'Будівництво «Офісно-лабораторного корпусу» у м. Городенка, 2015 р.<br>Реконструкція продуктового ринку та торгових павільйонів в м. Івано-Франківськ, 2015 р., 2017 р. та  2021 р.<br>Будівництво житлового будинку з вбудованими приміщеннями комерційного призначення в м. Калуш, 2015 р.<br>Будівництво вітрової електростанції ТОВ «ВІНД ЕНЕРДЖІ» в урочищі Обідній, Долинського району, 2016 р.<br>Будівництво екструдерної лінії ДП «Спецзалізобетон» в с. Ямниця, 2016 р. та 2018 р.<br>Будівництво багатоквартирних житлових будинків з вбудованими приміщеннями громадського призначення в м. Івано-Франківськ, 2016-2020 р.<br>Будівництво резиденції релігійної громади «Різдва Пресвятої Богородиці» Української Греко-Католицької Церкви в м. Івано-Франківськ, 2016 р.<br>Будівництво поліклініки Івано-Франківської Архієпархії УГКЦ в м. Івано-Франківську, 2016 р.<br>Будівництво адміністративної будівлі Івано-Франківської Архієпархії УГКЦ в м. Івано-Франківську, 2017 р.<br>Будівництво башти елеватора на терміналі перевантаження цементу ТДВ «Івано-Франківськцемент» в м. Івано-Франківськ, 2017 р.<br>Будівництво сімейного будинку готельного типу у с. Поляниця, 2019 р.<br>Реконструкція об`єктів інфраструктури ПрАТ «Івано-Франківськцемент» (силос клінкеру, цементний млин, майстерня), с. Ямниця,  2020-2021 р.<br>Будівництво естакади підвищеної колії 1п ДП «Спецзалізобетон» в с. Ямниця, 2020-2021 р.<br>Будівництво лінії стрічкових конвеєрів ТОВ «АГРО-СИНТЕЗ» ПОДІЛЛЯ» у с. Улашківці, Тернопільська обл., 2021 р.<br>Будівництво приватної садиби «Конопка» в с. Поляниця, 2022 р.<br>Реконструкція будівель заводу «Промприлад. Реновація» для створення інноваційного центру громадського призначення в м. Івано-Франківськ, 2022-2023 р. ',
      'h1-facility': 'Засновник',
      'h3-facility': 'Андрій Тимчук',
      'p-facility': 'Андрій Тимчук - власник Iren UPS з 17-річним досвідом у будівельній галузі. З 2006 року він займається будівництвом в Україні, та протягом останніх 3 років він швидко запускає та розвиває IrenUPS в Європі. Андрій Тимчук також є співвласником двох інших будівельних компаній: Монокарбуд та Citadel на Україні.',
      'h1-cta': 'Є питання? <br> Пишіть нам з будь-якого місця світу',
      'a-cta': 'Контакти',
      'footer-g': 'Обираючи нас, ви отримуєте надійного та кваліфікованого партнера, на якого можна покластися',
      'footer-g-love': 'створено з <i class="fa fa-heart-o"></i> IrenUPS',
      'h1-about': 'Місія та історія IrenUPS',
      'p-about': 'Основною метою, яку компанія завжди ставить перед собою, є максимізація задоволення клієнта. З цією метою будівельна фірма має сучасне обладнання та інструменти, а також висококваліфікований персонал. Наразі в компанії працює понад 120 працівників. Компанія IrenUPS - це будівельна фірма в Європі, яка успішно працює на ринку. Ми спеціалізуємося на будівництві житлових комплексів, індивідуальних будинків та мостів. Протягом короткого періоду роботи нас визнали надійними виконавцями, здатними реалізовувати складні та масштабні проекти в зазначені терміни. <br> 2006 - Початок діяльності будівельної компанії в Україні, ТОВ "МОНОКАРБУД". Виконавчим органом компанії є дирекція, яку очолює директор Андрій Тимчук. <br> 2017 - ТОВ "Монокарбуд" починає свою діяльність у Варшаві. Ведеться будівництво торгово-розважальних комплексів та житлових будівель. <br>2021 - Заснування компанії Iren Ups у Європі і її робота розвиток продовжується і зараз.',
      'h1-services-about':'Наші послуги та вміння:',
      'p-services-about':'1. Будівництво житлових комплексів:   - Розбудова багатоквартирних житлових будинків.<br>2. Будівництво індивідуальних будинків:- Освоєння будівництва особняків та приватних житлових об`єктів.<br>3. Будівництво комерційних об`єктів:   - Ведення проектів торгово-розважальних комплексів та інших комерційних споруд.<br>4. Інженерні роботи:- Виконання робіт, пов`язаних з тунелями, залізничними коліями та швидкісними дорогами.<br>5. Будівництво мостів та доріг:   - Розбудова та реконструкція мостів.- Будівництво швидкісних доріг та розв`язок.<br>6. Утилізація відходів та екологічні проекти:   - Розбудова муніципальних заводів з утилізації побутових відходів.- Реконструкція та модернізація муніципальних об`єктів з урахуванням екологічних стандартів.<br>7. Дизайнерські послуги:   - Пропозиції у сфері дизайну для житлових та комерційних об`єктів.<br>8. Реконструкція та термомодернізація:- Реконструкція та термомодернізація освітніх і культурних будівель.<br>9. Інші загальнобудівельні роботи:   - Розбудова і реконструкція різноманітних об`єктів, включаючи школи, культурні центри та інші громадські будівлі.<br>Це лише декілька прикладів наших досягнень та вмінь. Ми прагнемо максимально задовольняти потреби наших клієнтів і забезпечувати високий стандарт виконання будівельних проектів.',
      'contact-us': 'Зв\'яжіться з нами',
      'hsq': 'У вас є питання?',
      'street': 'вул. Вінцентего Поля, 18',
      'tel-time': 'Понеділок - п`ятниця, 10:00 - 18:00',
      'e-mail-desk': 'Надішліть нам своє запитання електронною поштою',
      'send-msg': 'Надіслати повідомлення',
      'policies':'Політика користування',
      'policies-1-h1':'Політика Забезпечення Якості',
      'policies-1-p':'1. Зобов`язання до Якості<br>Ми прагнемо досягти високого стандарту якості у всіх аспектах нашої діяльності. Це включає якість будівництва, надання послуг, спілкування з клієнтами та управління проектами.<br>2. Вдосконалення та Звітність<br>Ми регулярно оцінюємо наші процеси та проекти з метою виявлення можливостей для поліпшення якості. Наша компанія зобов`язана забезпечити звітність та відкритий обмін інформацією щодо заходів, призначених для підвищення якості.<br>3. Забезпечення Відповідності<br>Ми дотримуємося всіх відповідних стандартів та вимог у сфері будівництва та нерухомості, забезпечуючи відповідність усіх наших проектів із чинним законодавством та нормативними актами.<br>Ці політики призначені для забезпечення прозорості та дотримання наших високих стандартів у всіх аспектах діяльності компанії Iren UPS.',
      'policies-2-h1':'Політика Реклами та Маркетингу',
      'policies-2-p':'1. Рекламні Кампанії та Збір Інформації<br>Ми можемо запускати рекламні кампанії для просування наших продуктів та послуг. Під час цих кампаній ми можемо збирати агреговану інформацію про взаємодію з рекламою, таку як кількість переглядів та взаємодій.<br>2. Використання Особистої Інформації для Маркетингових Метей<br>Ми можемо використовувати зібрану особисту інформацію для персоналізації маркетингових матеріалів та пропозицій. Ми робимо це з метою підвищення релевантності та ефективності наших маркетингових зусиль.',
      'policies-3-h1':'Політика Конфіденційності',
      'policies-3-p':'Компанія Iren UPS прагне забезпечити максимальний рівень захисту особистих даних відвідувачів та клієнтів нашого веб-сайту. Це оголошення про конфіденційність пояснює, як ми збираємо, використовуємо, розкриваємо та захищаємо будь-яку інформацію, яку ви нам надаєте під час відвідування нашого сайту.<br>1. Збір та Використання Інформації<br>Ми можемо збирати особисту інформацію, таку як ім`я, контактна інформація та електронна пошта, коли ви взаємодієте з нашим веб-сайтом. Ця інформація використовується виключно для надання послуг та інформації, пов`язаної з нашою діяльністю.<br>2. Використання Файлів Cookie<br>Ми можемо використовувати файли cookie та інші технології відстеження для поліпшення зручності користувачів та збору агрегованої інформації про використання нашого сайту. Ви можете налаштувати свій веб-браузер для відмови від прийняття файлів cookie, але це може вплинути на деякі функції сайту.<br>3. Розкриття Інформації Третім Сторонам<br>Ми не розголошуємо особисту інформацію третім сторонам без вашого дозволу, за винятком випадків, коли це вимагається законом або необхідно для надання послуг, які ви запитали.<br>4. Заходи Безпеки<br>Ми застосовуємо відповідні технічні та організаційні заходи для захисту ваших особистих даних від несанкціонованого доступу та використання.<br>5. Зміни в Політиці Конфіденційності<br>Ця Політика Конфіденційності може час від часу оновлюватися. Будь ласка, періодично перевіряйте цю сторінку для ознайомлення з останніми змінами.<br>Зв`язок із нами<br>Якщо у вас є питання чи зауваження щодо нашої Політики Конфіденційності, будь ласка, зв`яжіться з нами за контактною інформацією.',
      'btn-text-one-translate': 'Більше проектів',
      'btn-text-two-translate': 'Клацніть!',
   
   },
   
   'de': {
      'home': 'STARTSEITE',
      'about': 'ÜBER UNS',
      'proj': 'PROJEKTE',
      'proj-title':'Projekte',
      'gallery': 'IMMOBILIEN',
      'contact': 'KONTAKT',
      'welcome' : 'Ihr zuverlässiger und technologisch fortschrittlicher <br> Partner im Bauwesen',
      'welcome2':'Zusätzliche Informationen',
      'about-iren':'Über IrenUPS',
      'gallery-1':'Immobilien',
      'contact-us':'Kontaktieren Sie uns',
      'h1-features':'Vorteile der Zusammenarbeit',
      'p-features' : 'Im Laufe unserer Arbeit haben wir das Vertrauen unserer Kunden und Partner durch die erfolgreiche Durchführung einer Reihe von wichtigen Projekten gewonnen.' ,
      'h3-1-features':'ERFAHRUNG',
      'p-1-features':'Unsere Spezialisten verfügen über eine langjährige Erfahrung in der Baubranche, die bis ins Jahr 2006 zurückreicht',
      'h3-2-features':'EIGENES TEAM',
      'p-2-features':'Der Eigentümer des Unternehmens, Andriy Tymchuk, ist Mitbegründer anderer erfolgreicher Bauunternehmen, was uns Zugang zu zusätzlichen Ressourcen und Fachwissen verschafft',
      'h3-3-features':'MULTIFUNKTIONALITÄT',
      'p-3-features':'Wir beschränken uns nicht auf eine Art des Bauens und haben Erfahrung in verschiedenen Bereichen, einschließlich Wohnkomplexen und Infrastruktureinrichtungen, Brücken.',
      'h1-campus': 'Unsere abgeschlossenen Projekte',
      'p-campus':'Mit uns haben Sie einen zuverlässigen und qualifizierten Partner an Ihrer Seite, dem Sie vertrauen können.',
      'cement-factory':'Zementwerk',
      'cement-factory-about': 'Implementierung energieeffizienter und umweltschonender Technologien auf der technologischen Linie Nr. 2 der Zementproduktion der AG "Ivano-Frankivskcement". Installation von Strukturen und Abdichtungen für den unterirdischen Teil der Transportgalerie.Die Bauarbeiten begannen im Jahr 2007 und dauern noch an.Arbeiten:<br>- Erdarbeiten zur Aushebung der Grube;<br>- Installation der Betonvorbereitung;<br>- Abdichtungsarbeiten (Geotextil, PVC-Membran - 2,0);<br>- Installation von Bewehrungsrahmen und Netzen (Böden, Wände, Decken);<br>- Betonierung der oben genannten Konstruktionen unter verschiedenen Winkeln der Betonmischungsablagerung.',
      'olsztyn':'Sportkomplex "Urania"',
      'olsztyn-about': 'Die Rekonstruktion und Erweiterung des Unterhaltungs- und Sportkomplexes "Urania" in Olsztyn, durchgeführt für den Stadtrat von Olsztyn im Zeitraum von 2021 bis 2023, spiegeln einen beeindruckenden Umfang der Arbeiten wider, die darauf abzielen, dieses Wahrzeichen zu verbessern und zu modernisieren. Die Arbeiter haben die Abdeckung der Kuppel mit thermischem Schweißdampf abgeschlossen und sie anschließend in einer silbernen Farbe gestrichen. Diese Arbeiten dauerten bis Mitte Juni. <br>Die Oberfläche der Kuppel beträgt 5 tausend Quadratmeter, und ihre Renovierung kann mit dem Flicken der Ferse eines Schuhs verglichen werden. Zweifellos ist das gesamte Gebäude in seinen Parametern weitläufig und beeindruckend. Das Volumen des Gebäudes beträgt 80 tausend Kubikmeter. Obwohl die Fläche, die es einnimmt, 4,1 tausend Quadratmeter beträgt, beträgt die Nutzfläche 7,7 tausend Quadratmeter.',
      'atmo':'Mehrparteien-Wohnhaus "Atmo"',
      'atmo-about': 'Der Bau des Mehrfamilienwohnkomplexes ATMO in Breslau für EIFFAGE POLSKA BUDOWNICTWO S.A., der von 2021 bis 2022 stattfand, umfasst einen Komplex aus zwei 6-stöckigen Gebäuden mit 113 hochwertigen Apartments von 26 bis 145 Quadratmetern. <br>Praktisch jede Wohnung verfügt über einen Balkon, eine Loggia oder eine Terrasse, während Erdgeschosswohnungen über eigene Gärten verfügen. Dank Panoramafenstern werden die Innenräume jeder Wohnung mit natürlichem Licht gefüllt. Die Bewohner haben auch die Möglichkeit, Klimaanlagen zu installieren. Der Komplex verfügt über 136 Parkplätze in der Tiefgarage, einen Fahrradabstellraum und 6 Gewerbeflächen im Erdgeschoss.',
      's16':'Straße S16 Olsztyn-Ełk',
      's16-about': 'Die Erweiterung der Schnellstraße S16 in der Woiwodschaft Ermland-Masuren ist bereits abgeschlossen. Der neue Abschnitt von Borki Wielkie nach Mrągowo ist über 16 km lang und verläuft in der Nähe der Dörfer Borki Wielkie, Sorkwity, Nowe Bagienice, Bagienice, Marcinowo und umgeht Mrągowo von Südwesten. Etwa 13 km der Strecke gehören zur Schnellstraße S16, und etwa 4 km stellen die Umgehung von Mrągowo dar, die entlang der Landstraße Nr. 59 verläuft. Die Straße auf dem Abschnitt der S16 hat einen zweispurigen Querschnitt mit zwei Spuren in jede Richtung. Auf dem Abschnitt der Umgehung von Mrągowo handelt es sich größtenteils um einen einspurigen Querschnitt (1x2). Der Zugang zur Schnellstraße ist nur über Verkehrslösungen möglich.',
      'hospital':'St. Lukas Krankenhaus',
      'school':'Lyzeum namens des heiligen Wassili der Große',
      'school-about': 'Bau des Verwaltungsgebäudes der Erzeparchie von Ivano-Frankivsk der UGKK in Ivano-Frankivsk, in der Shevchenko-Straße 11, im Auftrag der Erzeparchialverwaltung von Ivano-Frankivsk der Ukrainisch Griechisch-Katholischen Kirche. <br>Der Bau erfolgte in den Jahren 2017–2018.<br>Ein zweistöckiges Gebäude mit einer Gesamtfläche von 2188,14 m².',
      'hospital-about': 'Bau einer Klinik der Erzeparchie von Ivano-Frankivsk der UGKK in Ivano-Frankivsk, in der Garbarska-Straße 20,22,26 und Vasyl`yana-Straße 64, im Auftrag der Erzeparchialverwaltung von Ivano-Frankivsk der Ukrainisch Griechisch-Katholischen Kirche. <br>Der Bau erfolgte in den Jahren 2016–2017.<br>Ein sechsstöckiges Gebäude mit einem Technikgeschoss, mit einer Gesamtfläche von 5573,99 m².',
      'iren-all': 'Projekte IrenUPS',
      'iren-all-proj': '1. Bau eines Produktions- und Lagergebäudes mit sozialen und Büroflächen in Białeżyce für das Unternehmen SpaceFactory Sp. z o.o., 2021,<br>2. Umbau und Erweiterung des Freizeit- und Sportkomplexes „Urania“ in Allenstein, ausgeführt für den Stadtrat von Allenstein, 2021-2023,<br>3. Bau eines Mehrfamilienhauses ATMO in Breslau für EIFFAGE POLSKA BUDOWNICTWO S.A., 2021-2022,<br>4. Durchführung von Arbeiten im Zusammenhang mit Tunneln und Eisenbahngleisen für FLC BAU Sp. z o.o., 2022-2023,<br>5. Ausbau der städtischen Anlage zur Müllentsorgung für WARBUD S.A., 2022,<br>6. Bau der Schnellstraße S6 Słupsk-Gdańsk auf dem Abschnitt Bożepole Wielkie - Beginn der Umgehungsstraße Trójmiasto für PORR, 2022,<br>7. Bau der Straße S16 Allenstein (S51) - Lyck (S61), Abschnitt Borki Wielkie – Mrągowo, 2022-2023,<br>8. Bau der Straße S19 am Kreuz Kuźnica-Sokółka-Północ (mit Kreuzung), 2022-2023,<br>9. Bau eines Produktions- und Lagergebäudes in Breslau für FRONTIER ESTATES POLSKA MANAGEMENT SBU WROCŁAW SP. Z O.O., 2022,<br>10. Umbau und Erweiterung des Gebäudes des Palastes mit Änderung der Zweckbestimmung für die Bedürfnisse der Staatlichen Musikschule I. Grades in Krotochwin für DEFERO Sp. z o.o., 2022-2023,<br>',
      'iren-all-proj-2': '11. Arbeiten zur energetischen Sanierung im Rahmen des Umbaus und der Erweiterung des Gebäudes des Marschallamts der Woiwodschaft Opole (ul. Ostrówek 5-7, Oppeln) für DEFERO Sp. z o.o., 2022-2023,<br>12. Umbau und energetische Sanierung des Gebäudes der Wojciech-Kilar-Musikschule in Kattowitz gemäß Vertrag Nr. FT.2601.47.2020.ZO, abgeschlossen mit dem Zentrum für Kunstpädagogik und dem Komplex der Staatlichen Musikschulen, für DEFERO Sp. z o.o., 2022-2023,<br>13. Bauarbeiten: Bau des Zentrums für Kultur und Integration auf dem Marktplatz in Burzenin für DEFERO Sp. z o.o., 2022-2023,<br>14. Energetische Sanierung des Gebäudes der Grundschule Nr. 2 in Danzig, ul. Marusarzówny 10, im Rahmen des Projekts: „G1-Komplexe energetische Modernisierung von Bildungs- und Sportgebäuden der Gemeinde Danzig in den Jahren 2017-2020“ zusammen mit der Anpassung des Gebäudes an die geltenden Brandschutzbestimmungen, für DEFERO Sp. z o.o., 2022-2023,<br>15. Durchführung von Bauarbeiten: Energetische Sanierung des Gebäudes der Grundschule Nr. 12 Kornel Makuszyński in Piotrków Trybunalski, ul. Bełzańska 104/106, im Rahmen des Projekts, für DEFERO Sp. z o.o., 2022-2023,<br>16. Energetische Sanierung von öffentlichen Gebäuden in Kattowitz – Phase I, für DEFERO Sp. z o.o., 2022-2023,<br>17. Ausbau und Umbau der Grundschule Nr. 1 in Sułoszowa zusammen mit der Installation von OZE, für DEFERO Sp. z o.o., 2023,<br>18. Komplexe Modernisierung und Umbau des Gebäudes des städtischen Kulturzentrums in Głowno zusammen mit der Gestaltung des Geländes um das Gebäude für DEFERO Sp. z o.o., 2023,<br>19. Ausbau und Modernisierung der städtischen Mülldeponie in der ul. Zabrzeńska 2, Stadtteil Targówek, Warschau, für WYSOWA MOSTY Sp. z o.o., 2022-2023,<br>',
      'monokarbud-all': 'Monokarbud-Projekte',
      'monokarbud-all-proj': '- Chemische Behälter - "Flotatoren", 2006 <br>- Bau eines monolithisch-skelettalen Feuerschutzbehälters, 2007 <br>- Bau eines Mehrfamilienhauses, 2007 <br>- Inbetriebnahme der Produktionslinie für die Herstellung von OSB- und DSP-Platten, 2007 <br>- Umbau der Zementproduktion, Umstellung auf die Trockenherstellung <br>-Aqua-Park, Eisbahn (Ivano-Frankivsk), 2008 <br>-Wohnhaus monolithisch-skelettale Arbeiten 2008 -Einkaufszentrum „VELES-555“, 2008 <br>-Bau und Umbau einer industriellen Ölraffinerie (Nadvirna), 2008 <br>-Tank zur Lagerung von sauberem Wasser mit einem Fassungsvermögen von 10.000 m³, 2008 <br> -Anlage zur PVC-C-Produktion mit einer Kapazität von 300.000 Tonnen pro Jahr, 2009 <br>-Niederlassung "Terminal zur Umladung von Eisenbahnschienenzement" (Uzhgorod, OJSC "Ivano-Frankivskcement"), 2009 <br>-Mehrfamilienhaus, 2010, <br>Bau des Getreidetrockenkomplexes „RIELA“ in Horodenka, 2013 <br>Bau von Produktions- und Lagergebäuden für die LLC „Intelkom“, 2013 <br>Umbau der technologischen Linien der Zementproduktion der OJSC "Ivano-Frankivskcement", 2013-2014 <br>',
      'monokarbud-all-proj-2': 'Bau des „Büro-Laborgebäudes“ in Horodenka, 2015 <br>Umbau des Lebensmittelmarktes und der Handelspavillons in Ivano-Frankivsk, 2015, 2017 und 2021 <br>Bau eines Wohngebäudes mit integrierten gewerblichen Räumen in Kalush, 2015 <br>Bau des Windkraftwerks LLC "WIND ENERGY" im Gebiet Dolyna, 2016 <br>Bau der Extrusionslinie OJSC "Spezialbeton" im Dorf Yamnytsia, 2016 und 2018 <br>Bau von Mehrfamilienhäusern mit integrierten Räumen für öffentliche Zwecke in Ivano-Frankivsk, 2016-2020 <br>Bau der Residenz der religiösen Gemeinde „Geburt der Allerheiligsten Gottesmutter“ der Ukrainischen Griechisch-Katholischen Kirche in Ivano-Frankivsk, 2016 <br>Bau der Klinik der Erzeparchie der Griechisch-Katholischen Kirche in Lwiw in Ivano-Frankivsk, 2016 <br>Bau des Verwaltungsgebäudes der Erzeparchie der Griechisch-Katholischen Kirche in Lwiw in Ivano-Frankivsk, 2017 <br>Bau des Getreideaufzugsturms am Zementumschlagterminal der OJSC "Ivano-Frankivskcement" in Ivano-Frankivsk, 2017 <br>Bau eines familienartigen Hotelhauses im Dorf Polianytsia, 2019 <br>Umbau der Infrastrukturobjekte der PJSC "Ivano-Frankivskcement" (Klinkersilo, Zementmühle, Werkstatt), Dorf Yamnytsia, 2020-2021 <br>Bau einer erhöhten Bahngleisliftbrücke 1p PJSC "Spezialbeton" im Dorf Yamnytsia, 2020-2021 <br>Bau von Förderbandlinien LLC "AGRO-SYNTHESIS PODILLYA" im Dorf Ulashkivtsi, Region Ternopil, 2021 <br>Bau einer privaten Villa „Konopka“ im Dorf Polianytsia, 2022 <br>Umbau der Gebäude der Fabrik „Promprylad. Renovatsiya“ zur Schaffung eines innovativen Zentrums für öffentliche Zwecke in Ivano-Frankivsk, 2022-2023 <br>',
      
      'h1-facility':'Gründer',
      'h3-facility':'Andriy Tymchuk',
      'p-facility':'Andriy Tymchuk ist der Eigentümer von Iren UPS und verfügt über 17 Jahre Erfahrung in der Baubranche. Seit 2006 ist er im Baugewerbe in der Ukraine tätig, und in den letzten 2 Jahren hat er IrenUPS in Polen schnell eingeführt und entwickelt. Andriy Tymchuk ist außerdem Miteigentümer von zwei weiteren Bauunternehmen: Monokarbud und Citadel in der Ukraine.',
      'h1-cta' : 'Haben Sie Fragen? <br> Schicken Sie uns überall auf der Welt',
      'a-cta': ' Kontakte',
      'footer-g':'Wenn Sie sich für uns entscheiden, erhalten Sie einen zuverlässigen und qualifizierten Partner, dem Sie vertrauen können.',
      'footer-g-love': 'Mit <i class="fa fa-heart-o"></i> gemacht von IrenUPS', 
      'h1-about' : 'Aufgabe und Geschichte von IrenUPS' ,
      'p-about' : 'Das Hauptziel, das sich das Unternehmen immer setzt, ist die Maximierung der Kundenzufriedenheit. Zu diesem Zweck verfügt das Bauunternehmen über moderne Ausrüstung und Werkzeuge sowie hochqualifiziertes Personal. Derzeit beschäftigt das Unternehmen über 120 Mitarbeiter. IrenUPS ist ein Bauunternehmen in Europa, das erfolgreich am Markt tätig ist. Wir sind auf den Bau von Wohnkomplexen, Einzelhäusern und Brücken spezialisiert. In kurzer Zeit haben uns unsere Partner als zuverlässige Ausführer anerkannt, die in der Lage sind, komplexe und groß angelegte Projekte innerhalb festgelegter Fristen umzusetzen. <br> 2006 - Beginn der Bauaktivitäten des Unternehmens in der Ukraine, LLC "MONOKARBUD". Das Exekutivorgan des Unternehmens ist die Direktion unter der Leitung von Direktor Andriy Tymchuk.<br> 2017 - LLC "Monokarbud" nimmt seine Tätigkeit in Warschau auf und führt den Bau von Handels- und Unterhaltungskomplexen sowie Wohngebäuden durch. <br> 2021 - Gründung der Firma Iren Ups in Europa, und ihre Entwicklungsarbeit setzt sich fort.',
      'h1-services-about': 'Unsere Dienstleistungen und Fähigkeiten:',
      'p-services-about': '1. Bau von Wohnkomplexen: - Ausbau von Mehrfamilienhäusern.<br>2. Bau von Einfamilienhäusern: - Umsetzung von Projekten zum Bau von Villen und privaten Wohnobjekten.<br>3. Bau von Gewerbeobjekten: - Durchführung von Projekten für Handels- und Unterhaltungskomplexe sowie andere gewerbliche Gebäude.<br>4. Ingenieurbauarbeiten: - Durchführung von Arbeiten im Zusammenhang mit Tunneln, Eisenbahngleisen und Schnellstraßen.<br>5. Bau von Brücken und Straßen: - Ausbau und Rekonstruktion von Brücken.- Bau von Schnellstraßen und Verkehrsknotenpunkten.<br>6. Entsorgung von Abfällen und Umweltprojekte: - Bau von kommunalen Müllentsorgungsanlagen.- Rekonstruktion und Modernisierung von kommunalen Einrichtungen unter Berücksichtigung von Umweltstandards.<br>7. Designerdienstleistungen: - Vorschläge im Bereich Design für Wohn- und Geschäftsobjekte.<br>8. Rekonstruktion und Wärmedämmung: - Rekonstruktion und Wärmedämmung von Bildungs- und Kulturgebäuden.<br>9. Andere allgemeine Bauarbeiten: - Ausbau und Rekonstruktion verschiedener Objekte, einschließlich Schulen, Kulturzentren und anderer öffentlicher Gebäude.<br>Dies sind nur einige Beispiele unserer Leistungen und Fähigkeiten. Wir streben danach, die Bedürfnisse unserer Kunden maximal zu erfüllen und einen hohen Standard bei der Umsetzung von Bauprojekten sicherzustellen.',
      'contact-us' : 'Kontakt' ,
      'hsq':'Haben Sie noch Fragen?',
      'street':'Straße Wincentego Pola 18,',
      'tel-time':'Montag bis Freitag 10:00 bis 18:00',
      'e-mail-desk':'Senden Sie uns Ihre Anfrage per E-Mail.',
      'send-msg':'Eine Nachricht senden',
      'policies': 'Nutzungsrichtlinien',
      'policies-1-h1': 'Qualitätssicherungsrichtlinie',
      'policies-1-p': '1. Verpflichtung zur Qualität<br>Wir streben einen hohen Qualitätsstandard in allen Aspekten unserer Tätigkeit an. Dies umfasst die Qualität des Bauwesens, die Servicebereitstellung, die Kommunikation mit Kunden und das Projektmanagement.<br>2. Kontinuierliche Verbesserung und Transparenz<br>Wir bewerten regelmäßig unsere Prozesse und Projekte, um Möglichkeiten zur Verbesserung der Qualität zu identifizieren. Unser Unternehmen verpflichtet sich zu Transparenz und offenem Informationsaustausch über Maßnahmen zur Qualitätssteigerung.<br>3. Gewährleistung der Einhaltung<br>Wir halten uns an alle relevanten Standards und Anforderungen in der Bau- und Immobilienbranche und stellen sicher, dass alle unsere Projekte den geltenden Gesetzen und Vorschriften entsprechen.<br>Diese Richtlinien sollen Transparenz sicherstellen und die Einhaltung unserer hohen Standards in allen Bereichen der Geschäftstätigkeit von Iren UPS gewährleisten.',
      'policies-2-h1': 'Werbungs- und Marketingrichtlinie',
      'policies-2-p': '1. Werbekampagnen und Informationsbeschaffung<br>Wir können Werbekampagnen starten, um unsere Produkte und Dienstleistungen zu bewerben. Während dieser Kampagnen können wir aggregierte Informationen über die Interaktion mit der Werbung sammeln, wie z.B. die Anzahl der Aufrufe und Interaktionen.<br>2. Verwendung von persönlichen Informationen für Marketingzwecke<br>Wir können gesammelte persönliche Informationen zur Personalisierung von Marketingmaterialien und Angeboten verwenden. Dies tun wir, um die Relevanz und Effektivität unserer Marketingbemühungen zu steigern.',
      'policies-3-h1': 'Datenschutzrichtlinie',
      'policies-3-p': 'Das Unternehmen Iren UPS strebt danach, den höchsten Schutz für die persönlichen Daten der Besucher und Kunden unserer Website zu gewährleisten. Diese Datenschutzerklärung erläutert, wie wir Informationen sammeln, verwenden, offenlegen und schützen, die Sie uns bei Ihrem Besuch auf unserer Website zur Verfügung stellen.<br>1. Sammlung und Verwendung von Informationen<br>Wir können personenbezogene Daten wie Namen, Kontaktdaten und E-Mail sammeln, wenn Sie mit unserer Website interagieren. Diese Informationen werden ausschließlich verwendet, um Dienstleistungen und Informationen im Zusammenhang mit unseren Geschäftsaktivitäten bereitzustellen.<br>2. Verwendung von Cookies<br>Wir können Cookies und andere Tracking-Technologien verwenden, um die Benutzerfreundlichkeit zu verbessern und aggregierte Informationen über die Nutzung unserer Website zu sammeln. Sie können Ihren Webbrowser so konfigurieren, dass er Cookies ablehnt, dies kann jedoch Auswirkungen auf einige Funktionen der Website haben.<br>3. Offenlegung gegenüber Dritten<br>Wir geben personenbezogene Informationen ohne Ihre Zustimmung nicht an Dritte weiter, es sei denn, dies ist gesetzlich vorgeschrieben oder zur Erbringung der von Ihnen angeforderten Dienstleistungen erforderlich.<br>4. Sicherheitsmaßnahmen<br>Wir setzen angemessene technische und organisatorische Maßnahmen ein, um Ihre persönlichen Daten vor unbefugtem Zugriff und Gebrauch zu schützen.<br>5. Änderungen der Datenschutzrichtlinie<br>Diese Datenschutzrichtlinie kann von Zeit zu Zeit aktualisiert werden. Überprüfen Sie diese Seite regelmäßig auf die neuesten Änderungen.<br>Kontaktieren Sie uns<br>Wenn Sie Fragen oder Bedenken zu unserer Datenschutzrichtlinie haben, kontaktieren Sie uns bitte unter den angegebenen Kontaktdaten.',
      'btn-text-one-translate': 'Mehr Projekte',
      'btn-text-two-translate': 'Klicken!',
      
   }
   
};

$(document).ready(function () {
   var langCode = getCookie("lang") || 'en';

   updateSelectedLanguageDisplay(langCode);

   updatePageContent(langCode);

   $('.translate, .dropdown-content a').click(function () {
      var lang = $(this).attr('key') || $(this).attr('id');
      setCookie("lang", lang, 365); 
      updatePageContent(lang);
      updateSelectedLanguageDisplay(lang);
      hideMenu(); 
   });

   function updatePageContent(lang) {
      $('.lang').each(function (index, item) {
         var key = $(this).attr('key');
         $(this).html(arrLang[lang][key]);
      });
      $('#example-content').html(arrLang[lang]['home']);
   }

   function updateSelectedLanguageDisplay(lang) {
      var imagePath = "./" + lang + "-lang-1.png";
      $('#selectedLangIcon').attr('src', imagePath);
      $('#selectedLang').hide();
   }

   function setCookie(name, value, days) {
      var expires = "";
      if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toUTCString();
      }
      document.cookie = name + "=" + (value || "") + expires + "; path=/";
   }

   function getCookie(name) {
      var nameEQ = name + "=";
      var ca = document.cookie.split(';');
      for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') c = c.substring(1, c.length);
            if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
      }
      return null;
   }

   function showMenu() {
      $('#navLinks').animate({ right: '0' }, 200);
      $('#selectedLang').show();
   }

   function hideMenu() {
      $('#navLinks').animate({ right: '-200px' }, 200);
      $('#selectedLang').hide(); 
   }
});

$('.scroll-btn').on('click', function(event) {
   event.preventDefault();

   var targetId = $(this).attr('href');
   $('html, body').animate({
      scrollTop: $(targetId).offset().top
   }, 1000); 
});


